MOVE MACRO ADDRESS1,N,ADDRESS2
    MOV SI,OFFSET ADDRESS1  ;源串指针初值
    MOV DI,OFFSET ADDRESS2  ;目的串指针初值
    MOV CX,N ;设置循环次数
    CLD
    REP MOVSB ;将 DS:SI 这段地址的N 个字节复制到 ES:DI 
ENDM;定义宏

DATA SEGMENT
    N EQU 25
    STRING1 DB "ABCDEFGHIJKLMN1234567890"
    STRING2 DB N DUP(?)
DATA ENDS;数据段

;代码段
CODE SEGMENT
    ASSUME CS:CODE,DS:DATA
START:
    MOV AX,DATA
    MOV DS,AX ;复制地址 DI:SI
    MOV ES,AX ;设置好被复制的地址
    MOVE STRING1,N,STRING2  ;调用宏
    MOV AX,4C00H ;调用中断
    INT 21H
CODE ENDS
END START
